site_name: DeepESDL
site_url: http://127.0.0.1:8000/
copyright: Copyright Â© 2022 by the DeepESDL Team
theme: readthedocs  # alternative: mkdocs

nav:
  - Home:
    - Index: index.md
  - User guide:
    - Getting Started: guide/user-guide.md
    - DeepESDL JupyterLab: guide/jupyterlab.md
    - DeepESDL xcube viewer: guide/xcube-viewer.md
    - DeepESDL datacubes: guide/datacubes.md
    - DeepESDL datacube generation: guide/datacube-generation.md
    - Further information: guide/further-information.md
  - Design:
    - Index: design/index.md
  - ML Toolkit:
    - Index: ml-toolkit/index.md
  - Datasets:
    - List of datasets: datasets/datasets.md
    - Earth System Data Cube: datasets/ESDC.md
    - Baltic Sea Cube: datasets/baltic-sea.md
    - Black Sea Cube: datasets/black-sea.md

plugins:
  - search
  - mkapi

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
  - attr_list
